# Generated by Django 4.2.9 on 2024-01-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='district',
            field=models.CharField(choices=[('D1', 'TRIVANDRUM'), ('D2', 'KOLLAM'), ('D3', 'ALAPPUZHA'), ('D4', 'ERNAKULAM'), ('D5', 'KOZHIKODE')], max_length=100),
        ),
    ]
